apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-function-app
  labels:
    app: hello-function-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-function-app
  template:
    metadata:
      labels:
        app: hello-function-app
    spec:
      containers:
        - name: hello-function-app
          image: testedotnet.azurecr.io/teste-dot-net:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: AzureWebJobsStorage
              value: "UseDevelopmentStorage=true"
            - name: FUNCTIONS_WORKER_RUNTIME
              value: "dotnet-isolated"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"